### ISSUE TITLE
Neu setzen der Variable helligkeit nicht nötig

### ISSUE THREAD

**Issue by reuta** [hoersamu/Genuino-101-Heartrate#3]
led_fader.ino **Z.24:** 
`
if (helligkeit == 0)
  {
    helligkeit = 0; 
    delay (250); 
    fadeschritte = -fadeschritte; 
}
`
Das setzen der variable helligkeit auf 0 ist in diesem Fall unnötig, da ja bei dieser if-Anweisung sowieso fest stehen muss, dass helligkeit = 0 ist.

**Comment by hoersamu** [comment]
bereinigt
